import type { FlatMenu } from '@/interface/menu.d'

export const flatMenus: FlatMenu[] = [
    {
        id: '0',
        name: '首页',
        path: 'home',
        component: '/src/views/home/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '首页',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '1',
        name: '用户管理',
        path: 'user',
        type: 'dir',
        title: '用户管理',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '2',
        name: '用户管理',
        path: 'user',
        component: '/src/views/user/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '用户管理',
        icon: 'el|menu',
        cache: true,
        parentId: '1',
    },
    {
        id: '3',
        name: '权限管理',
        path: 'permission',
        component: '/src/views/user/permission/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '权限管理',
        icon: 'el|menu',
        cache: true,
        parentId: '1',
    },
    {
        id: '4',
        name: '角色管理',
        path: 'role',
        component: '/src/views/user/role/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '角色管理',
        icon: 'el|menu',
        cache: true,
        parentId: '1',
    },
    {
        id: '10',
        title: 'material-manager',
        name: 'material-manager',
        path: 'material-manager',
        type: 'dir',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '20',
        title: '商城管理',
        name: 'mall-manager',
        path: 'mall-manager',
        type: 'dir',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '21',
        title: '商品管理',
        name: 'product-manager',
        path: 'product-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/product/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '22',
        title: '订单管理',
        name: 'order-manager',
        path: 'order-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/order/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '11',
        title: '材料管理',
        name: '材料管理',
        path: 'material-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/material/index.vue',
        handleType: 'route',
        parentId: '10'
      },
    {
        id: '12',
        title: '材料标签管理',
        name: '材料标签管理',
        path: 'material-tags',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/material/material-tags/index.vue',
        handleType: 'route',
        parentId: '10'
      },
      {
        id: '13',
        title: '材料分类管理',
        name: '材料分类管理',
        path: 'material-category',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/material/material-category/index.vue',
        handleType: 'route',
        parentId: '10'
      },
]