import type { FlatMenu } from '@/interface/menu.d'

export const flatMenus: FlatMenu[] = [
    {
        id: '0',
        name: '首页',
        path: 'home',
        component: '/src/views/home/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '首页',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '1',
        name: '用户管理',
        path: 'user',
        type: 'dir',
        title: '用户管理',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '2',
        name: '用户管理',
        path: 'user',
        component: '/src/views/user/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '用户管理',
        icon: 'el|menu',
        cache: true,
        parentId: '1',
    },
    {
        id: '3',
        name: '权限管理',
        path: 'permission',
        component: '/src/views/user/permission/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '权限管理',
        icon: 'el|menu',
        cache: true,
        parentId: '1',
    },
    {
        id: '4',
        name: '角色管理',
        path: 'role',
        component: '/src/views/user/role/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '角色管理',
        icon: 'el|menu',
        cache: true,
        parentId: '1',
    },
    {
        id: '5',
        name: '地址管理',
        path: 'address-manager',
        component: '/src/views/user/address/index.vue',
        handleType: 'route',
        type: 'menu',
        title: '地址管理',
        icon: 'el|menu',
        cache: true,
        parentId: '1',
    },
    {
        id: '10',
        title: 'material-manager',
        name: 'material-manager',
        path: 'material-manager',
        type: 'dir',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '20',
        title: '商城管理',
        name: 'mall-manager',
        path: 'mall-manager',
        type: 'dir',
        icon: 'el|menu',
        cache: true,
    },
    {
        id: '21',
        title: '品牌管理',
        name: 'brand-manager',
        path: 'brand-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/product/brand/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '24',
        title: '分类管理',
        name: 'category-manager',
        path: 'category-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/product/category/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '25',
        title: 'SPU管理',
        name: 'spu-manager',
        path: 'spu-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/product/spu/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '26',
        title: 'SKU管理',
        name: 'sku-manager',
        path: 'sku-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/product/sku/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '27',
        title: '购物车管理',
        name: 'cart-manager',
        path: 'cart-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/product/cart/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '28',
        title: '订单管理',
        name: 'order-manager',
        path: 'order-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/product/order/index.vue',
        handleType: 'route',
        parentId: '20'
    },
    {
        id: '11',
        title: '材料管理',
        name: '材料管理',
        path: 'material-manager',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/material/index.vue',
        handleType: 'route',
        parentId: '10'
      },
    {
        id: '12',
        title: '材料标签管理',
        name: '材料标签管理',
        path: 'material-tags',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/material/material-tags/index.vue',
        handleType: 'route',
        parentId: '10'
      },
      {
        id: '13',
        title: '材料分类管理',
        name: '材料分类管理',
        path: 'material-category',
        type: 'menu',
        icon: 'el|menu',
        cache: true,
        component: '/src/views/material/material-category/index.vue',
        handleType: 'route',
        parentId: '10'
      },
    {
        id: '30',
        title: '店铺管理',
        name: 'store-manager',
        path: 'store-manager',
        type: 'dir',
        icon: 'el|shop',
        cache: true,
    },
    {
        id: '31',
        title: '首页背景图',
        name: 'store-home-bg',
        path: 'home-bg',
        type: 'menu',
        icon: 'el|picture',
        cache: true,
        component: '/src/views/store/home-bg/index.vue',
        handleType: 'route',
        parentId: '30'
    },
    {
        id: '32',
        title: '首页轮播',
        name: 'store-home-carousel',
        path: 'home-carousel',
        type: 'menu',
        icon: 'el|files',
        cache: true,
        component: '/src/views/store/home-carousel/index.vue',
        handleType: 'route',
        parentId: '30'
    },
    {
        id: '33',
        title: '店铺资料',
        name: 'store-profile',
        path: 'profile',
        type: 'menu',
        icon: 'el|info-filled',
        cache: true,
        component: '/src/views/store/profile/index.vue',
        handleType: 'route',
        parentId: '30'
    }
]